golemfactory/ya-runtime-vm

- init-container/proto.h
Protocol template, will probably need to be adjusted during implementation.
Closes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/2)
> Host <-> Guest protocol description

- Cargo.toml
- README.md
- conf/ya-runtime-vm.json
- src/main.rs
resolves #13
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/19)
> support running, when installed from deb

- Cargo.lock
- Cargo.toml
- src/main.rs
related to #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/23)
> oxidize gvmkit run

- init-container/Makefile
- init-container/include/process_bookkeeping.h
- init-container/include/proto.h
- init-container/src/init.c
- init-container/src/process_bookkeeping.c
- src/guest_agent_comm.rs
- src/main.rs
- src/response_parser.rs
This commit adds process bookkeeping in Guest Agent, makes process
spawning asynchronous and handles asynchronous notifications.
Closes #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/22)
> Add process bookkeeping

- init-container/src/init.c
- src/guest_agent_comm.rs
- src/main.rs
Resolves #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/26)
> Add process killing

- init-container/include/proto.h
- init-container/src/init.c
- src/guest_agent_comm.rs
- src/main.rs
Adds one of the features from #4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/29)
> Add setting of process current working directory

- init-container/src/init.c
- src/response_parser.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/27)
> don't encode exit status

- init-container/include/proto.h
- init-container/src/init.c
- runtime/src/guest_agent_comm.rs
- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/32)
> Add entrypoint running

- init-container/Makefile
- init-container/include/communication.h
- init-container/include/proto.h
- init-container/src/communication.c
- init-container/src/init.c
- runtime/src/guest_agent_comm.rs
- runtime/src/main.rs
Closes #31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/37)
> Add host <-> guest directories sharing

- runtime/src/guest_agent_comm.rs
- runtime/src/main.rs
Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/40)
> Add proper handling of errors in `reader` task

- init-container/include/process_bookkeeping.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/45)
> add missing header

- init-container/Makefile
- init-container/include/communication.h
- init-container/include/cyclic_buffer.h
- init-container/include/process_bookkeeping.h
- init-container/include/proto.h
- init-container/src/communication.c
- init-container/src/cyclic_buffer.c
- init-container/src/init.c
- init-container/tests/.gitignore
- init-container/tests/cyclic_buffer.c
- runtime/src/main.rs
Closes #35, closes #41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/42)
> Add process output buffering

- gvmkit/src/docker.rs
- gvmkit/src/image_builder.rs
- init-container/Makefile
- init-container/src/init.c
- runtime/examples/direct.rs
- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/49)
> Fix missing /dev/random + CWD

- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/55)
> Enable KVM

- gvmkit/src/upload.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/60)
> gvmkit: display image hash on upload

- runtime/Cargo.toml
- runtime/init-container/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/62)
> version bump

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/cpu.rs
- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/63)
> Offer template CPU architecture details

- runtime/examples/direct.rs
- runtime/init-container/include/proto.h
- runtime/init-container/src/init.c
- runtime/src/guest_agent_comm.rs
- runtime/src/main.rs
Fix the current implementation where no stderr output is captured and no notifications are reported
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/69)
> [fix] Capture and notify on stderr

- runtime/init-container/src/init.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/75)
> Fixed max overlay upperdir/workdir size in ram

- Cargo.lock
- runtime/Cargo.toml
- runtime/init-container/Makefile
- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/77)
> Default working directory for processes

- runtime/init-container/src/init.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/79)
> Don't terminate on waitpid error in SIGCHLD handler

- runtime/init-container/Makefile
Resolves #82
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/83)
> Kernel 5.10.26

- runtime/init-container/Makefile
Extracted from one of internal conversations when supporting our community users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/88)
> Containter makefile description within comments

- Cargo.lock
- runtime/Cargo.toml
- runtime/examples/commands.rs
- runtime/src/guest_agent_comm.rs
- runtime/src/main.rs
Makes use of Runtime API 0.2 for sequential event processing.
Requires https://github.com/golemfactory/yagna/pull/1305
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/90)
> Runtime API 0.2

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/examples/commands.rs
- runtime/src/deploy.rs
- runtime/src/lib.rs
- runtime/src/main.rs
`ya-runtime-vm` based on `ya-runtime-sdk`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/89)
> Runtime SDK implementation

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/92)
> Upgrade ya-runtime-sdk rev

- runtime/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/101)
> Runtime capabilities in offer template

- .github/workflows/release.yml
- runtime/Cargo.toml
- runtime/image/rootfs.qcow2
- runtime/init-container/Makefile
- runtime/init-container/src/init.c
- runtime/src/deploy.rs
- runtime/src/main.rs
This reverts commit b5d3d9e9b13753edf5fd5399799ecdadc51ed649.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/106)
> Revert "Root overlay filesystem (#100)"

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/examples/commands.rs
- runtime/src/cpu.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/102)
> ya-runtime-sdk v0.2

- runtime/init-container/src/init.c
- removes and closes process' open file descriptors when the output buffer is empty
- closes the unused parent pipe part prior to `execve`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golemfactory/ya-runtime-vm/107)
> Fix pipe file descriptor leak

- .gitignore
- runtime/src/main.rs
Resolves https://github.com/golemfactory/yagna/issues/1875
> Manifest_support runtime capability

- Cargo.lock
- runtime/examples/network.rs
- runtime/init-container/include/network.h
- runtime/init-container/src/init.c
- runtime/init-container/src/network.c
Limits the maximum packet size for sending with UDP
> Lower VPN Network MTU

- runtime/src/main.rs
Starts the entrypoint defined in the metadata according to docker rules:
- if ENTRYPOINT or CMD is present but the other is missing, the command defined by the setting will be executed
- if both is present then CMD is concatenated to ENTRYPOINT to use it as parameter(s) and the extended command is executed
If the `start_entrypoint` flag is defined for Start command but the metadata does not define an entrypoint then an error will be returned without starting the VM.
Solves #93 
Resolves https://github.com/golemfactory/yagna/issues/1350
> Start VM entrypoint when flag is set in Start command

- .gitignore
- runtime/init-container/Makefile
- runtime/init-container/include/process_bookkeeping.h
- runtime/init-container/src/cyclic_buffer.c
- runtime/init-container/src/init.c
- runtime/init-container/tests/cyclic_buffer.c
Fix waiting for all output being processed before closing task execution.
Fixes: https://github.com/golemfactory/yagna/issues/2035
> Fix stdout fragmentation

- runtime/src/main.rs
> Add capability for start-entrypoint

- runtime/init-container/include/init-seccomp.h
This caused the build to fail.
> Add missing header file

- runtime/init-container/src/init.c
Since device nodes are not created automatically, looking for them isn't a good test to detect GPU passthrough. Instead, consider GPU passthrough enabled if nvidia kernel modules are there.
Device nodes needs to be created manually according to documentation at: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#device-node-verification This is likely due to the kernel API for doing it automatically being unavailable for non-GPL drivers.
> Load nvidia kernel modules and create device nodes
